const express = require('express');
const boardController = require('../Controllers/boardController');
const route = express.Router();
const auth = require("../Middlewares/auth");
route.post('/:workspaceId/:boardId/add-member',auth.verifyToken, boardController.addMember);
route.put('/:workspaceId/:boardId/update-background', auth.verifyToken, boardController.updateBackground);
route.put('/:workspaceId/:boardId/update-board-description',  auth.verifyToken,boardController.updateBoardDescription);
route.put('/:workspaceId/:boardId/update-board-title',auth.verifyToken, boardController.updateBoardTitle);
route.post('/create',auth.verifyToken, boardController.create);
route.get('/:workspaceId/:boardId', auth.verifyToken, boardController.getById);
route.delete('/:workspaceId/:boardId',auth.verifyToken, boardController.deleteById);
route.get('/:workspaceId/:boardId/activity', auth.verifyToken, boardController.getActivityById);
route.get('/:workspaceId',  auth.verifyToken, boardController.getAll);
module.exports = route;
